### ISSUE TITLE
unable to import topy in windows

### ISSUE THREAD

**Issue by nagordon** [williamhunter/ToPy#42]
Not really sure where I went wrong, but do you have any insight to this error. I am using windows 10

```
Python 2.7.15 | packaged by conda-forge | (default, May  8 2018, 14:46:56) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import topy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxxx\Anaconda3\envs\py27\lib\site-packages\topy\__init__.py", line 10, in <module>
    from .elements import *
  File "C:\Users\xxxx\Anaconda3\envs\py27\lib\site-packages\topy\elements.py", line 47, in <module>
    Q4bar = load(fname)
  File "C:\Users\xxxx\Anaconda3\envs\py27\lib\site-packages\numpy\lib\npyio.py", line 372, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'C:\\Users\\xxxx\\Anaconda3\\envs\\py27\\lib\\site-packages\\topy\\data\\Q4bar.K'
>>>
```

also, per your comment about pysparse on windows, conda has a package that installs easily
https://anaconda.org/guyer/pysparse

Thanks. Looking forward to exploring topy

**Comment by williamhunter** [comment]
Hi Neal,

It looks like the Q4bar.K file is missing in that location. ToPy is
*supposed* to create the *.K files (all of them) if they don't exist,
usually this is only required once (SymPy is required for the integration).
I'm pretty sure it will be one of two things:

   1. Which version of ToPy are you using? You should use this one:
   https://github.com/williamhunter/topy/releases/tag/v0.4.0
   2. Check if you perhaps need Admin rights, it may be that Windows is
   blocking ToPy from creating the *.K files there.

I'm glad Pysparse can be installed via Conda, that should make things a lot
easier. I suppose I should get ToPy onto Conda at some point...

Regards,
William

**Comment by letianwang92** [comment]
Hi Dear William,

Thanks for the effort on the code. I am using mac and installed the topy today. But I am running into the same problem as Neal. 
I looked into your elements.py. It excepts IOError. Is it something caused the problem?
Your help is greatly appreciated.

Sincerely,
Letian

`Traceback (most recent call last):
  File "optimise.py", line 8, in <module>
    import topy
  File "/usr/local/lib/python2.7/site-packages/topy/__init__.py", line 10, in <module>
    from .elements import *
  File "/usr/local/lib/python2.7/site-packages/topy/elements.py", line 47, in <module>
    Q4bar = load(fname)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/topy/data/Q4bar.K'`

**Comment by williamhunter** [comment]
Hi Letian,

Which version of ToPy did you download? Don't clone, the master branch is bugged-up. Download and install this one: https://github.com/williamhunter/topy/releases/tag/v0.4.0

If it is not that, it may be a permissions issue. When ToPy runs for the first time, it needs to create the element stiffness matrices (*.K files). If ToPy does not have write access, it cannot create the *.K files, and then it will fail. You can see in the Python traceback above that it is looking for Q4bar.K, which obviously doesn't exist on your machine.

Regards,
William

**Comment by williamhunter** [comment]
> Hi Letian,
> 
> Which version of ToPy did you download? Don't clone, the master branch is bugged-up. Download and install this one: https://github.com/williamhunter/topy/releases/tag/v0.4.0
> 
> If it is not that, it may be a permissions issue. When ToPy runs for the first time, it needs to create the element stiffness matrices (*.K files). If ToPy does not have write access, it cannot create the *.K files, and then it will fail. You can see in the Python traceback above that it is looking for Q4bar.K, which obviously doesn't exist on your machine.
> 
> Regards,
> William

I assume that did it?

**Comment by ashcic** [comment]
Hi William,

I had the same problem as @letianwang92 , and I tried the different methods that you mentioned, but with no success.

The first time (and all the times since) that I ran Topy, I didn't see the line "	It seems as though all or some of the element stiffness matrices do not exist. Creating them..."

I'm using numpy-1.13.1 (having rolled back from 1.16) and pysparse 1.3.  Would these have any baring on the situation?

Any suggestions about how I can get this up and running would be greatly appreciated!


Ash

**Comment by williamhunter** [comment]
Hi Ash,

I'm sorry about that. I recently (as in a week ago) started fiddling with ToPy again and decided I want to move it to Python 3, especially since Python 2 is not supported anymore. I didn't think people would be using it 10 years after I finished my studies, but here we are...

I also tried to get it working on Windows 10 this past weekend, but without success. It's all down to Pysparse basically and the ensuing nightmare of recompiling 'GNU-based' software on Windows using Cygwin or Mingw. Linking, libs, odd compiler flags, libs that are missing or have the wrong names, etc., it's hell on Windows and discouraging if all you want to do is get results. I'm a mechanical engineer so that probably doesn't help either!

Installing via conda-forge (https://anaconda.org/conda-forge/pysparse) is perhaps an option if I compare my woes with the FiPy team, but also only for Python 2 by the looks of it. Looks like the FiPy project is considering PETSc or Trilinos for the future, but interestingly they also note that Pysparse is generally the faster solver.

R,
William

**Comment by williamhunter** [comment]
I forgot to add, CHOLMOD is another option, and there are wrappers for Python. But let me first see if I can at least get ToPy to work with Python 2 again. I'm going to use the Anaconda distribution simply because conda makes life easy and I like how it handles virtual environments.

**Comment by ashcic** [comment]
Hi William,

Thanks for your quick reply, and all the hard work that you have put into this!  

I really should get using Linux, but I'm quite keen on building some kind of Rhino/Grasshopper interface, to quickly set up the definitions, and that only runs on PC or Mac. I'll try it with Anaconda, and see if I can get things moving.  

Great to hear that you are thinking about developing it on Python 3 too.  

Thanks again,


Ash

**Comment by williamhunter** [comment]
Hi Ash

I don't know if you're using 'conda' (Anaconda's package manager, similar to 'pip'), but you can try to install Pysparse using **conda-forge** in the meantime, as there is a 'feedstock' (their name for a repository) for Pysparse. Instructions here: https://anaconda.org/conda-forge/pysparse

If you don't use the Anaconda distribution, you should perhaps consider it. 'conda' makes it easy to manage virtual environments, install 'normal' Python packages and also _feedstocks_, as well as allowing you to still use 'pip'. The virtual environments is a game changer for me, but then I'm easy to impress...

William

**Comment by williamhunter** [comment]
Hi again, there is a new release (v0.4.1) that works on Windows via conda...

https://github.com/williamhunter/topy/releases/latest

**Comment by ashcic** [comment]
Worked perfectly!

One thing missing in the installation notes was to install pyvtk `conda install -c conda-forge pyvtk`

Thanks again,


Ash

**Comment by williamhunter** [comment]
You're right, I forgot about the VTK dependency. Will add it to the install instructions.

Glad it worked out for you. I've started working on a Python 3.8 version...
