### ISSUE TITLE
how to make it work on python 3 as pysparse is not compatible with python 3

### ISSUE THREAD

**Issue by eg10yx** [williamhunter/ToPy#50]

**Comment by oguztoragay** [comment]
I have the same question because I can see the potential improvements in this package.

**Comment by williamhunter** [comment]
Not sure. Pysparse was (still is?) the fastest library for solving sparse linear problems, the others I tested were always terribly slow. But that might also be due to my coding, who knows.

You basically have to find a fast sparse solver that can be used in the place of Pysparse. CHOLMOD is an option.
